MedicalWebApplication/Models/ErrorViewModel.cs
using System;

namespace MedicalWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MedicalWebApplication/Controllers/AuthController.cs
using MedicalWebApplicationService.IService;
using MedicalWebApplicationService.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MedicalWebApplication.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authServcie;

        public AuthController(IAuthService authServcie)
        {
            _authServcie = authServcie;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var validate = await _authServcie.Register(model);
                if (validate)
                {
                    return RedirectToAction("Login", "Auth");
                }
                ModelState.AddModelError(string.Empty, "Email Already exist");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            var user = await _authServcie.Login(model);
            if (user != null)
            {
                HttpContext.Session.SetString("FullName", user.FullName);
                HttpContext.Session.SetString("UserId", user.UserId);
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError(string.Empty, "User does not exist");
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

MedicalWebApplication/Controllers/DoctorController.cs
using MedicalWebApplicationService.IService;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MedicalWebApplication.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService _doctorServices;
        public DoctorController(IDoctorService doctorServices)
        {
            _doctorServices = doctorServices;
        }
        public async Task<IActionResult> Doctor(int id)
        {

            return View(await _doctorServices.GetDoctorById(id));
        }
    }
}

MedicalWebApplication/Controllers/HomeController.cs
using MedicalWebApplication.Models;
using MedicalWebApplicationService.IService;
using MedicalWebApplicationService.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MedicalWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService _productService;
        private readonly IResearchStatisticsService _researchStatisticsService;
        private readonly IDoctorService _doctorServices;

        public HomeController(ILogger<HomeController> logger, IProductService productService, IResearchStatisticsService researchStatisticsService, IDoctorService doctorServices)
        {
            _logger = logger;
            _productService = productService;
            _researchStatisticsService = researchStatisticsService;
            _doctorServices = doctorServices;
        }

        public async Task<IActionResult> Index(int page)
        {
            var products = await _productService.GetAllProducts();
            PaginationViewModel paginationViewModel = new PaginationViewModel();
            /*------------------------------------------------------------------------------*/
            paginationViewModel.PageSize = 4;
            paginationViewModel.CurrentPage = page == 0 ? 1 : page;

            double pages = (double)products.Count / paginationViewModel.PageSize;
            paginationViewModel.NumberPages = (int)Math.Round(pages, 0, MidpointRounding.AwayFromZero);
            var skip = 4 * (Convert.ToInt32(paginationViewModel.CurrentPage) - 1);
            paginationViewModel.Products = products.Skip(skip).Take(paginationViewModel.PageSize).ToList();

            if (paginationViewModel.CurrentPage == 1)
            {
                paginationViewModel.PreviousPage = 0;
            }
            else
            {
                paginationViewModel.PreviousPage = paginationViewModel.CurrentPage - 1;
            }
            if (paginationViewModel.CurrentPage != pages)
            {
                paginationViewModel.NextPage = paginationViewModel.CurrentPage + 1;
            }
            paginationViewModel.Research = await _researchStatisticsService.Calstat();
            paginationViewModel.Doctors = await _doctorServices.GetAllDoctorsAsync();
            /*---------------------------------------------------------------------------------*/

            return View(paginationViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MedicalWebApplication/Views/Doctor/Doctor.cshtml
@model DoctorViewModel
@{
    ViewData["Title"] = "Index";
}

 <div class="profile-doc">
   <img src="@Model.ImageUrl" class="profile-img-doc" />
   <div class="profile-content-doc">
       <p class="profile-signature">@Model.Name</p>
       <p class="profile-profile-doc">@Model.Profile</p>
   </div>
 </div> 






@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MedicalWebApplication/Views/Home/Index.cshtml
@model PaginationViewModel;
@{
    ViewData["Title"] = "Home Page";
    var fullName = Context.Session.GetString("FullName");

}
<body>
    <img src="~/images/📷 Image (1).svg" alt="Chef" class="display-img" />

    <article class="article-c">
        <div class="article">
            <p class="article-text1">Our gloves are holding hands with research teams at the American Cancer Society.</p>
            <p class="article-text2">Gloves with a Purpose <sup>TM</sup> from SYNA Medical</p>
            <p class="article-text3">
                Since 1946, the American Cancer Society (ACS), the nation’s #1 trusted source for cancer information,
                has invested more than $5 billion in cancer research to find better treatments, uncover causation factors,
                and improve patient care and quality of life. <br /><br />
                SYNA Medical is a proud supporter of ACS and with our breakthrough Gloves with a PurposeTM campaign, you can be too.
            </p>
        </div>
    </article>
    @* ---------------------------------------------------------------------Dynamically Generated----------------------------------------------------------------------------*@
    @if (fullName != null)
    {
        @foreach (var item in Model.Doctors)
        {
            if (item.Id == 1)
            {
                <section class="profile">
                    <img src="@item.ImageUrl" class="profile-img" />
                    <div class="profile-info">
                        <a asp-controller="Doctor" asp-action="Doctor" asp-route-id="@item.Id" class="profile-info-name">@item.Name</a>
                        <p class="profile-info-bio">@item.Comment</p>
                    </div>
                </section>
            }
            else if (item.Id == 2)
            {
                <section class="profile">
                    <div class="profile-info">
                        <a asp-controller="Doctor" asp-action="Doctor" asp-route-id="@item.Id" class="profile-info-name">@item.Name</a>
                        <p class="profile-info-bio">@item.Comment</p>
                    </div>
                    <img src="@item.ImageUrl" class="profile-img" />
                </section>
            }
            else
            {
                <section class="profile3">
                    <img src="@item.ImageUrl" class="profile3-img" />
                    <a asp-controller="Doctor" asp-action="Doctor" asp-route-id="@item.Id" class="profile3-name">@item.Name</a>
                    <div class="profile3-info">
                        <p class="profile3-bio">@item.Comment</p>
                    </div>
                </section>
            }
        }

    }
    else
    {
        @foreach (var item in Model.Doctors)
        {
            if (item.Id == 1)
            {
                <section class="profile">
                    <img src="@item.ImageUrl" class="profile-img" />
                    <div class="profile-info">
                        <a asp-controller="Auth" asp-action="Register" asp-route-id="@item.Id" class="profile-info-name">@item.Name</a>
                        <p class="profile-info-bio">@item.Comment</p>
                    </div>
                </section>
            }
            else if (item.Id == 2)
            {
                <section class="profile">
                    <div class="profile-info">
                        <a asp-controller="Auth" asp-action="Register" asp-route-id="@item.Id" class="profile-info-name">@item.Name</a>
                        <p class="profile-info-bio">@item.Comment</p>
                    </div>
                    <img src="@item.ImageUrl" class="profile-img" />
                </section>
            }
            else
            {
                <section class="profile3">
                    <img src="@item.ImageUrl" class="profile3-img" />
                    <a asp-controller="Auth" asp-action="Register" asp-route-id="@item.Id" class="profile3-name">@item.Name</a>
                    <div class="profile3-info">
                        <p class="profile3-bio">@item.Comment</p>
                    </div>
                </section>
            }
        }
    }
    @* ---------------------------------------------------------------------Dynamically Generated----------------------------------------------------------------------------*@
    <div class="container">
        <section class="profile4">
            @foreach (var item in Model.Products)
            {
                <div class="profile4-content">
                    <img src="@item.ProductImageUrl" class="profile4-content-img" />
                    <p class="profile4-content-text1">@item.ProductName</p>
                    <p class="profile4-content-text2">@item.ProductDescription</p>
                    <a href="@item.ProductLink">Read more></a>
                </div>
            }
        </section>

        <nav aria-label="Page navigation" class="page-navigtion">
            <ul class="pagination">
                <li class="page-item d-flex align-items-center">
                    <a href=""><i class="fa fa-chevron-left"></i></a>
                    <a class="page-link ml-2" asp-route-page="@Model.PreviousPage">
                        Prev
                    </a>
                </li>
                @for (int i = 1; i <= Model.NumberPages; i++)
                {
                    <li class="page-item ">
                        @if (Model.CurrentPage == i)
                        {
                            <a class="page-link" asp-route-page="@i" style="background-color:blue;">
                                @i
                            </a>
                        }
                        else
                        {
                            <a class="page-link" asp-route-page="@i">
                                @i
                            </a>
                        }

                    </li>
                }

                <li class="page-item d-flex align-items-center">
                    <a class="page-link mr-2" asp-route-page="@Model.NextPage">
                        Next
                    </a>
                    <a href=""><i class="fa fa-chevron-right"></i></a>
                </li>
            </ul>
        </nav>
    </div>
    @* ---------------------------------------------------------------------Dynamically Generated----------------------------------------------------------------------------*@

    <section class="section-donate">
        <div class="section-donate-content">
            <p class="section-donate-content-cancer">Woman cancer</p>
            <p class="section-donate-content-gap">Close the <br />Care Gap</p>
            <div class="section-donate-button"><button>Donate</button></div>
            <img src="~/images/wc1.svg" alt="Lady's image" class="section-donate-content-img" />
        </div>
        <div class="section-donate-content">
            <p class="section-donate-content-cancer">Woman cancer</p>
            <p class="section-donate-content-gap">Close the <br />Care Gap</p>
            <div class="section-donate-button"><button>Donate</button></div>
            <img src="~/images/wc1.svg" alt="Lady's image" class="section-donate-content-img" />
        </div>
    </section>
    <section class="section-gloves">
        <div class="section-gloves-content">
            <p class="section-gloves-content-txt1">Gloves with a<br />porpouse</p>
            <p class="section-gloves-content-txt2">Lorem Ipsum is simply dummy <br /> text of the printing and <br />typesetting industry. Lorem <br /> Ipsum is simply dummy text of <br /> the printing and </p>
            <div class="section-gloves-content-button"><button>Learn more</button></div>
        </div>
        <img src="~/images/Gloves Box - Mockup 02 2.png" alt="Alternate Text" class="section-gloves-img-img" />
    </section>
    <section class="section-donate-2">
        <div class="section-donate-2-content">
            <p class="section-donate-2-content-cancer">Woman cancer</p>
            <p class="section-donate-2-content-gap">Close the Care Gap</p>
            <div class="section-donate-2-button"><button>Donate</button></div>
            <img src="~/images/wc1.svg" alt="Lady's image" class="section-donate-2-content-img" />
        </div>
    </section>
    <br />
    <br />
    <section class="section-facts">
        @* ---------------------------------------------------------------------Research Statistics Generated----------------------------------------------------------------------------*@
        <div>
            <div class="section-facts-content">
                <span class="section-facts-content-figure"> <sup class="section-facts-content-symbol">$</sup> @Model.Research.NewResearch</span>
                <a href="#" class="section-facts-content-link">New Research</a>
            </div>
        </div>
        <div>
            <div class="section-facts-content">
                <span class="section-facts-content-figure support"><sup class="section-facts-content-symbol support">%</sup> @Model.Research.CancerSupport</span>
                <a href="#" class="section-facts-content-link support">Cancer Support</a>
            </div>
        </div>
        <div>
            <div class="section-facts-content research">
                <span class="section-facts-content-figure x">@Model.Research.CancerResearch</span>
                <a href="#" class="section-facts-content-link">Cancer Research</a>
            </div>
        </div>
        @* ---------------------------------------------------------------------Research Statistics Generated----------------------------------------------------------------------------*@
    </section>
    <br />
    <br />
    <section class="section-contact">
        <div class="section-contact-content">
            <img src="~/images/email (1).svg" alt="email-logo" class="section-contact-content-img" />
            <p class="section-contact-content-txt">It was popularised<br />in the 1960s with</p>
            <a href="#" class="section-contact-content-link">Read more</a>
        </div>
        <div class="section-contact-content">
            <img src="~/images/recycle.svg" alt="recycle=logo" class="section-contact-content-img" />
            <p class="section-contact-content-txt">Lorem Ipsum</p>
            <a href="#" class="section-contact-content-link">Read more</a>
        </div>
        <div class="section-contact-content">
            <img src="~/images/brokenImage (1).svg" alt="" class="section-contact-content-img" />
            <p class="section-contact-content-txt">Aldus PageMaker<br />including</p>
            <a href="#" class="section-contact-content-link">Read more</a>
        </div>
    </section>
</body>

MedicalWebApplication/Views/Shared/_AuthLayOut.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medicals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="header-img bg-dark">
        <nav class="navbar navbar-expand-sm navbar-nav ml-auto navbar-dark">
            <ul class="nabar-nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Auth" asp-action="Register" class="nav-link">Register</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Auth" asp-action="Login" class="nav-link">Login</a>
                </li>
            </ul>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="footer-container">
            <img src="~/images/footerLogo.svg" alt="Logo" />
            <div class="footer-container-img">
                <a href="#"><img src="~/images/Vector.svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/images/Vector (1).svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/images/Vector (2).svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/images/Vector (3).svg" alt="Alternate Text" /></a>
            </div>
        </div>
        <div class="footer-info">
            <div class="footer-info-message">
                <p class="footer-info-message">
                    Thank you for subscribing to our newsletter.[Your company name]
                    team will work hard to deliver good quality information in the fields you have specified upon subscription.
                    However, if you decide that you no longer want to receive such emails from us, feel free to click the link below.
                </p>
            </div>
            <div><a href="#">Unsuscribe</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">View in browser</a></div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MedicalWebApplication/Views/Shared/_Layout.cshtml
@{
    var fullName = Context.Session.GetString("FullName");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medicals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="header-img">

        <nav class="navbar navbar-expand-sm navbar-nav ml-auto">
            @if (fullName != null)
            {
                <div class="navbar-brand">
                    <img src="~/images/🚣 Logo Center (Row For Content Columns).svg" alt="Logo" />
                </div>
                <a><img src="~/images/Avatar.jpg" height="30" width="30"></a>
                <ul class="navbar-nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a asp-controller="" asp-action="" class="nav-link">Welcome @fullName</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Auth" asp-action="Logout" class="nav-link">Logout</a>
                    </li>
                </ul>
            }
            else
            {
                <div class="navbar-brand">
                    <img src="~/images/🚣 Logo Center (Row For Content Columns).svg" alt="Logo" />
                </div>
                <ul class="navbar-nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Auth" asp-action="Register" class="nav-link">Register</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Auth" asp-action="Login" class="nav-link">Login</a>
                    </li>
                </ul>
            }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="footer-container">
            <img src="~/images/footerLogo.svg" alt="Logo" />
            <div class="footer-container-img">
                <a href="#"><img src="~/images/Vector.svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/images/Vector (1).svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/images/Vector (2).svg" alt="Alternate Text" /></a>
                <a href="#"><img src="~/images/Vector (3).svg" alt="Alternate Text" /></a>
            </div>
        </div>
        <div class="footer-info">
            <div class="footer-info-message">
                <p class="footer-info-message">
                    Thank you for subscribing to our newsletter.[Your company name]
                    team will work hard to deliver good quality information in the fields you have specified upon subscription.
                    However, if you decide that you no longer want to receive such emails from us, feel free to click the link below.
                </p>
            </div>
            <div><a href="#">Unsuscribe</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">View in browser</a></div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>